version: '3'
services:
  zookeeper:
    environment:
      ZOOKEEPER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper2:2888:3888,zookeeper3:2888:3888
    image: zookeeper:3.6.3
    ports:
      - "2181:2181"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - my-network

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka1:9092,OUTSIDE://localhost:29092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181,zookeeper2:2182,zookeeper3:2183
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    networks:
      - my-network

  producer-service:
    build: ./producer-service
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - my-network

  consumer-service:
    build: ./consumer-service
    ports:
      - "8081:8080"
    depends_on:
      - kafka
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - my-network

networks:
  my-network:
    driver: bridge